### ISSUE TITLE
Create a Binder deployment for future workshops

### ISSUE THREAD

**Issue by andrewphilipsmith** [maps-as-data/MapReader#232]
**Is your feature request related to a problem? Please describe.**

For new users, the process of installing MapReader can be painful and frustrating - particularly when the user is unfamiliar with conda/commandline tools etc, or some do not yet know whether MapReader is a good solution to their problem.

**Describe the solution you'd like**

It would be useful to have some way where users can try out MapReader without having to go through the hassle of installing everything. This would be useful when during workshops/presentations and when users are making an initial exploration of MapReader. Because this would just be for exploration - this doesn't need to be something that scales for large map collections.

Binder would be a good platform for this.

**Describe alternatives you've considered**
Google Colab might also be a suitable platform.

**Additional context**
This idea was attempted in early 2022, but at the time we did not achieve a reliable solution. Below are some tickets from the time:
https://github.com/Living-with-machines/MapReader/issues/36
https://github.com/Living-with-machines/MapReader/issues/35
https://github.com/Living-with-machines/MapReader/issues/34
https://github.com/Living-with-machines/MapReader/issues/21

**Comment by kallewesterling** [comment]
I think we can close this, with reference to the two new issues:

- [ ] #425 
- [ ] #437

What do you think @rwood-97

**Comment by rwood-97** [comment]
Yep agree, happy to close this
