### ISSUE TITLE
plan sprint for integrating text detection & recognition

### ISSUE THREAD

**Issue by kmcdono2** [maps-as-data/MapReader#358]
Input: patches
Output: bounding polygon defined by pixel coordinates + detected text + [eventually ordered, grouped words]

**Prelim experiment:**
- [x] #359

Next Steps:
- [x] if patches as input, method for connecting patches in order to identify bounding polygons reaching across patches
- [ ] design that allows for training data input, even if we are not training for our initial task
- [ ] deezymatch for post-recognition task, developing the dictionary for this that is not OSM data
- [ ] define output format, ideally both:
  - [x] geojson, with unique IDs for each feature that could somehow be comparable across versions
  - [ ] ALTO https://github.com/altoxml 

Timing:
- March 2024 for prelim experiment
- post ICDAR competition review state of the art, next steps

TODO:
- [x] @kmcdono2 send @rwood-97 recogito output example

Considerations:
- font style https://lme.tf.fau.de/person/christlein/ 
- training data for the ICDAR MapText competition https://zenodo.org/records/10656556
- sample data for the ICDAR MapText competition https://zenodo.org/records/10444913

**Comment by rwood-97** [comment]
https://github.com/fundamentalvision/Deformable-DETR
https://github.com/mlpc-ucsd/TESTR/tree/main

**Comment by kmcdono2** [comment]
@rwood-97 - there are examples of mapKurator output for 25" 1st ed OS maps here: https://github.com/machines-reading-maps/os-data/tree/main/labels (each directory is a separate sheet)

**Comment by rwood-97** [comment]
https://github.com/facebookresearch/detectron2/issues/2820#issue-841754372 adding link to this issue so I don't lose it, how can we have detectron2 as a dependency

**Comment by kmcdono2** [comment]
Let's test out the work @fedenanni is doing on the task of font clustering. I'll open a separate ticket about this.

**Comment by rwood-97** [comment]
shall I shut this issue?
