### ISSUE TITLE
Create a sample/examples folder with some highlighted maps/patches which are good for workshops

### ISSUE THREAD

**Issue by rwood-97** [maps-as-data/MapReader#393]

**Comment by rwood-97** [comment]
I have started this for the workshop in April/May 2024 using 6 maps for glasgow area. 
They are in a google drive [here](https://drive.google.com/drive/folders/14tSvFbH2DJSnuRX1B9dA7Ic9JhzVPmc1?usp=sharing)

We should work out if we want to expand this further.

**Comment by kmcdono2** [comment]
Return to this in terms of what we need for June workshop.
