### ISSUE TITLE
apply for GPU RSE support

### ISSUE THREAD

**Issue by kmcdono2** [maps-as-data/MapReader#469]
Funding opportunity:

GPU eCSE support provides funding to the UKRI research community to develop software in a sustainable manner to run on GPU-based architectures. We invite proposals to develop software that facilitates research targeted at UKRI’s digital research infrastructure e.g. future Exascale supercomputing services, UK national AI services, national Tier-2 HPC services. The call is open to research across all of UKRI’s remit.

The 2nd GPU eCSE call (GPU-eCSE02) opened on the 2 July 2024. The final deadline for proposal submission is 16:00 on 17 September 2024 via the ARCHER2 SAFE. Please note that for this call there is no separate technical evaluation stage or separate technical evaluation form. Funding will enable the employment of an RSE (a Research Software Engineer, PDRA or equivalent) to work specifically on the relevant software to enable new features or improve the performance of the software to be run on GPU-based architectures. Funding can be requested for up to 24 person months of effort per project for a duration of up to 2 calendar years. There is flexibility in the way the effort is requested. For example, a project may have more than one person working on it or the effort could be spread over a greater number of calendar months, i.e. a staff member could work on the project at less than 100% alongside other commitments or it could be worked on by a staff member who doesn’t work full time. Please just get in contact with the ARCHER2 Service Desk ([support@archer2.ac.uk](mailto:support@archer2.ac.uk)) if you wish to discuss possible scenarios. Projects are expected to start between 1 January and 1 July 2025, and be completed by 31 March 2027. Funding can be requested for staff located at the institution of the PI, third parties, or can include staff from the ARCHER2 centralised CSE support team at EPCC or a mixture of the above.

Projects may utilise the GPU component of ARCHER2 or other suitable GPU resources to complete the technical work. If the proposal plans to use the GPU component of ARCHER2, successful projects will be given access to these resources. If projects plan to utilise other systems, you should ensure you have suitable resources available to complete the project successfully. Please contact and arrange this access with the relevant service provider before submission.

More details of how to apply are available by following the link to the eCSE calls page from here: [https://www.archer2.ac.uk/ecse/calls/](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.archer2.ac.uk%2Fecse%2Fcalls%2F&data=05%7C02%7Ckmcdonough%40TURING.AC.UK%7C124a65ffefcc4b05965a08dcafb4b8d8%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C638578437955434040%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=UnmorXXE0lhbVKwLfc1WxLJ1zOQzgzXPsPXHi0PxXy8%3D&reserved=0)

Deadline for final GPU-eCSE02 submission: 16:00 on 17 Sep 2024 (via the ARCHER2 SAFE: [https://safe.epcc.ed.ac.uk/](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsafe.epcc.ed.ac.uk%2F&data=05%7C02%7Ckmcdonough%40TURING.AC.UK%7C124a65ffefcc4b05965a08dcafb4b8d8%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C638578437955446619%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=BcY31psyVXDo14b6lEtAGMOgag%2BW34Mw%2FclY9URTIUw%3D&reserved=0))

**Comment by kallewesterling** [comment]
This deadline is quickly approaching. We need to prioritise this if we are going to submit a proposal.

**Comment by kmcdono2** [comment]
I will at it to my todo ist for next week.

**Comment by kmcdono2** [comment]
- I have emailed Pieter about handling naming Turing peopl
- I have not heard back from ARCHER team about naming one of them centrally
- I will let the Bristol person know we are applying, maybe they would be interested?
- I have shared the proposal draft google doc on slack
- If we go ahead, and people are named as members or Co-Is I will need a CV from anyone fulfilling a technical role. And I will need a 250 word statement about your contribution from everyone. Details in the doc.

**Comment by kallewesterling** [comment]
Just to be clear: this is the one that is a no-go now, @kmcdono2?

**Comment by kmcdono2** [comment]
Correct, we are not applying for this now.

**Comment by kallewesterling** [comment]
Putting this back into the "freezer" in the project board.
