### ISSUE TITLE
Consider moving MapReader to its own github organisation

### ISSUE THREAD

**Issue by rwood-97** [maps-as-data/MapReader#484]
https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

- [x] Check with Ruth
- [x] To do before JOSS paper release?
- [x] Identify any risks?

If happy:
- [x] Create org
- [x] Add any required contributors 
- [x] Update JOSS paper

**Comment by rwood-97** [comment]
if we do this, how do we deal with links in papers etc.?
Can we add redirects?

@kallewesterling any ideas?

**Comment by kallewesterling** [comment]
I think if we transfer the repo, GitHub keeps track of it for us... I'll see if I can find more info

**Comment by rwood-97** [comment]
- [ ] Create org + do test repo transfer

**Comment by rwood-97** [comment]
Alternative org names could be: 
- MapReader-org
- MapReader-hub
- MapReader-research 
- MapReader-code
- ?? please add suggestions
