### ISSUE TITLE
Suggestion: Ignore patches that are completely empty

### ISSUE THREAD

**Issue by mradamcox** [maps-as-data/MapReader#509]
**Is your feature request related to a problem? Please describe.**
Many georeferenced maps will be oriented at an angle, while the entire file itself is rectangular. When patches are created, this can result in patches that are completely empty--all pixels are "no value". Skipping these patches altogether could speed up the patchify process (and everything that comes later).

![image](https://github.com/user-attachments/assets/2a32a0fb-9ff3-4afa-9050-cdd2d995f90a)

```
map.patchify_all(method="pixel", patch_size=1000)
```

![image](https://github.com/user-attachments/assets/6efe71f0-e662-4709-bf21-8ab8fbf292eb)

**Describe the solution you'd like**
I'm wondering if there would be any negative downstream effects of simply skipping these patches during the patchifyl process, so that they are not processed. For example, a check [here](https://github.com/maps-as-data/MapReader/blob/main/mapreader/load/images.py#L1280) could just skip the save and add_to_parent operations if a patch only has no data values in it (checking for what is truly "no data" would be the tricky part, but that should be in the metadata of the file, I think...).

**Additional context**
May be best to have this as a flag in the patchify_all() method.

GeoTIFF (COG) shown above:
[alexandria_la_1896_p3_1__jwYGc9_00.zip](https://github.com/user-attachments/files/17231567/alexandria_la_1896_p3_1__jwYGc9_00.zip)

**Comment by rwood-97** [comment]
Hi, I think this is a great idea - it's not something we'd come across since most of our maps are from a tilelayer and so don't have huge amounts of blank space but it makes total sense for people using individual sheets.

Do you want to have a go at doing this (we'd be very excited to get a outside contribution to the code) or if not I'm happy to add it to my list of upcoming things to do.

**Comment by mradamcox** [comment]
Great, I'd be happy to try to work on this soon. Will make a PR when I can.

**Comment by mradamcox** [comment]
Ultimately it looks like this is going to be just a few lines of a change in `MapImages()._patchify_by_pixel()`. I see that `_patchify_by_pixel_square()` is slated for deprecation. Should I add this new flag in there as well, or just ignore that method as it will be gone soon?

**Comment by rwood-97** [comment]
I think safe to ignore it, we just needed to keep it for some analysis of old data we had which used it

**Comment by kallewesterling** [comment]
👏 👏 👏 👏 👏 

@mradamcox This was our first external PR and we're very, very grateful for you work!!

@all-contributors please add @mradamcox for code, test ✨

**Comment by kallewesterling** [comment]
@all-contributors please add @mradamcox for code, test ✨

**Comment by mradamcox** [comment]
@kallewesterling Great! Thanks for the help along the way.
